package com.company.secureapispring.common.auth;

import lombok.Getter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;

import java.util.Collection;

/**
 * The CustomJwtAuthenticationToken will append two more information to the JWT token generated by keycloak
 */
@Getter
public class CustomJwtAuthenticationToken extends JwtAuthenticationToken {

    private final Long organizationId;
    private final Long userId;

    public CustomJwtAuthenticationToken(
        Jwt jwt,
        Collection<? extends GrantedAuthority> authorities,
        String name,
        Long userId,
        Long organizationId
    ) {
        super(jwt, authorities, name);
        this.organizationId = organizationId;
        this.userId = userId;
    }

}
