#!/bin/bash
set +x

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 <DB_NAME> <DB_USERNAME> <DB_PASSWORD>"
  exit 1
fi

DB_NAME=$1
DB_USERNAME=$2
DB_PASSWORD=$3
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "
    CREATE ROLE ${DB_USERNAME}
    WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS
    PASSWORD '${DB_PASSWORD}'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "
    CREATE DATABASE ${DB_NAME}
    WITH OWNER = ${DB_USERNAME} ENCODING = 'UTF8'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_USERNAME" -c "
    GRANT ALL ON SCHEMA public to ${DB_NAME}"
