apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ${PROJECT_ARTIFACT}-${ENV_NAME}
  name: ${PROJECT_ARTIFACT}-${ENV_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${PROJECT_ARTIFACT}-${ENV_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${PROJECT_ARTIFACT}-${ENV_NAME}
      name: ${PROJECT_ARTIFACT}-${ENV_NAME}
      namespace: ${NAMESPACE}
      annotations:
        kubernetes.io/change-cause: "${CHANGE_CAUSE}"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              value: ${NAMESPACE}
            - name: APP_VERSION
              value: "${APP_VERSION}"
            - name: BUILD_NUMBER
              value: "${BUILD_NUMBER}"
          envFrom:
            - configMapRef:
                name: ${PROJECT_ARTIFACT}-${ENV_NAME}
                optional: false
            - secretRef:
                name: ${PROJECT_ARTIFACT}-${ENV_NAME}
                optional: false
          image: ${REMOTE_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: ${PROJECT_ARTIFACT}-${ENV_NAME}
          ports:
            - containerPort: ${SPRING_APP_PORT}
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 128Mi
      imagePullSecrets:
        - name: registry-credentials
