pipeline {
    options {
      timeout(time: 10, unit: 'MINUTES')
      disableConcurrentBuilds()
    }
    agent {
        // Must have Docker Pipeline and Docker Commons Plugin Installed
        dockerfile {
            filename 'Dockerfile'
            dir 'src/main/jenkins'
            args """
                -u root:root
                -v /root/.m2:/root/.m2
                -v /var/run/docker.sock:/var/run/docker.sock
            """
        }
    }
    stages {
        stage('Test') {
            steps {
                sh './mvnw clean test'
            }
            // Must have JaCoCo plugin installed
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    step( [ $class: 'JacocoPublisher' ] )
                }
            }
        }
        stage('Build') {
            steps {
                sh """
                    ./mvnw -DskipTests package
                    echo "TODO Build image and push to registry"
                """
            }
        }
        stage('Deploy') {
            steps {
                sh """
                    echo "TODO Deploy on self hosted"
                """
            }
        }
    }
}