---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: secure-api-spring
  name: secure-api-spring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secure-api-spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secure-api-spring
      namespace: default
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: secure-api-spring-cfg-map
          image: ${registryHost}/secure-api-spring:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: secure-api-spring
          ports:
            - containerPort: ${springAppPort}
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: secure-api-spring
  name: secure-api-spring
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: ${springAppPort}
  selector:
    app.kubernetes.io/name: secure-api-spring
  type: ClusterIP
